version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "18:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "11:00"
      timezone: Europe/Rome
