version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "18:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "next"
      - dependency-name: "@next/font"
      - dependency-name: "eslint-config-next"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "11:00"
      timezone: Europe/Rome
