name: Pull request CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install packages
        run: npm ci

      - name: Format check
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build content
        run: npm run build:content

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build
